/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Consultas realizadas por entidades comerciales.
 */
@ApiModel(description = "Consultas realizadas por entidades comerciales.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class ComercialesInner {
  @SerializedName("ultimos3meses")
  private Integer ultimos3meses = null;

  @SerializedName("ultimos12meses")
  private Integer ultimos12meses = null;

  @SerializedName("ultimos24meses")
  private Integer ultimos24meses = null;

  @SerializedName("mas24meses")
  private Integer mas24meses = null;

  public ComercialesInner ultimos3meses(Integer ultimos3meses) {
    this.ultimos3meses = ultimos3meses;
    return this;
  }

   /**
   * Consultas en los último 3 meses.
   * @return ultimos3meses
  **/
  @ApiModelProperty(example = "2")
  public Integer getUltimos3meses() {
    return ultimos3meses;
  }

  public void setUltimos3meses(Integer ultimos3meses) {
    this.ultimos3meses = ultimos3meses;
  }

  public ComercialesInner ultimos12meses(Integer ultimos12meses) {
    this.ultimos12meses = ultimos12meses;
    return this;
  }

   /**
   * Consultas en los últimos 12 meses.
   * @return ultimos12meses
  **/
  @ApiModelProperty(example = "2")
  public Integer getUltimos12meses() {
    return ultimos12meses;
  }

  public void setUltimos12meses(Integer ultimos12meses) {
    this.ultimos12meses = ultimos12meses;
  }

  public ComercialesInner ultimos24meses(Integer ultimos24meses) {
    this.ultimos24meses = ultimos24meses;
    return this;
  }

   /**
   * Consultas en los últimos 24 meses.
   * @return ultimos24meses
  **/
  @ApiModelProperty(example = "2")
  public Integer getUltimos24meses() {
    return ultimos24meses;
  }

  public void setUltimos24meses(Integer ultimos24meses) {
    this.ultimos24meses = ultimos24meses;
  }

  public ComercialesInner mas24meses(Integer mas24meses) {
    this.mas24meses = mas24meses;
    return this;
  }

   /**
   * Consultas en más de 24 meses.
   * @return mas24meses
  **/
  @ApiModelProperty(example = "9")
  public Integer getMas24meses() {
    return mas24meses;
  }

  public void setMas24meses(Integer mas24meses) {
    this.mas24meses = mas24meses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComercialesInner comercialesInner = (ComercialesInner) o;
    return Objects.equals(this.ultimos3meses, comercialesInner.ultimos3meses) &&
        Objects.equals(this.ultimos12meses, comercialesInner.ultimos12meses) &&
        Objects.equals(this.ultimos24meses, comercialesInner.ultimos24meses) &&
        Objects.equals(this.mas24meses, comercialesInner.mas24meses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ultimos3meses, ultimos12meses, ultimos24meses, mas24meses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComercialesInner {\n");
    
    sb.append("    ultimos3meses: ").append(toIndentedString(ultimos3meses)).append("\n");
    sb.append("    ultimos12meses: ").append(toIndentedString(ultimos12meses)).append("\n");
    sb.append("    ultimos24meses: ").append(toIndentedString(ultimos24meses)).append("\n");
    sb.append("    mas24meses: ").append(toIndentedString(mas24meses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
