/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * Datos de consultas.
 */
@ApiModel(description = "Datos de consultas.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class ConsultasRCEInner {
  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  @SerializedName("nombreOtorgante")
  private String nombreOtorgante = null;

  @SerializedName("tipoCredito")
  private String tipoCredito = null;

  @SerializedName("importeCredito")
  private Integer importeCredito = null;

  @SerializedName("claveUnidadMonetaria")
  private String claveUnidadMonetaria = null;

  public ConsultasRCEInner fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Fecha de la consulta.
   * @return fechaConsulta
  **/
  @ApiModelProperty(example = "2020-01-09")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ConsultasRCEInner nombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
    return this;
  }

   /**
   * Contiene el Nombre del Otorgante de Crédito que reporto el Crédito. Ver Tabla: Tipo de Negocio. &lt;br&gt;Nota: Este elemento solo es reportado para reporte de crédito especial.
   * @return nombreOtorgante
  **/
  @ApiModelProperty(example = "CC MICROFINANZAS")
  public String getNombreOtorgante() {
    return nombreOtorgante;
  }

  public void setNombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
  }

  public ConsultasRCEInner tipoCredito(String tipoCredito) {
    this.tipoCredito = tipoCredito;
    return this;
  }

   /**
   * Get tipoCredito
   * @return tipoCredito
  **/
  @ApiModelProperty(example = "F")
  public String getTipoCredito() {
    return tipoCredito;
  }

  public void setTipoCredito(String tipoCredito) {
    this.tipoCredito = tipoCredito;
  }

  public ConsultasRCEInner importeCredito(Integer importeCredito) {
    this.importeCredito = importeCredito;
    return this;
  }

   /**
   * Get importeCredito
   * @return importeCredito
  **/
  @ApiModelProperty(example = "0")
  public Integer getImporteCredito() {
    return importeCredito;
  }

  public void setImporteCredito(Integer importeCredito) {
    this.importeCredito = importeCredito;
  }

  public ConsultasRCEInner claveUnidadMonetaria(String claveUnidadMonetaria) {
    this.claveUnidadMonetaria = claveUnidadMonetaria;
    return this;
  }

   /**
   * Get claveUnidadMonetaria
   * @return claveUnidadMonetaria
  **/
  @ApiModelProperty()
  public String getClaveUnidadMonetaria() {
    return claveUnidadMonetaria;
  }

  public void setClaveUnidadMonetaria(String claveUnidadMonetaria) {
    this.claveUnidadMonetaria = claveUnidadMonetaria;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsultasRCEInner consultasRCEInner = (ConsultasRCEInner) o;
    return Objects.equals(this.fechaConsulta, consultasRCEInner.fechaConsulta) &&
        Objects.equals(this.nombreOtorgante, consultasRCEInner.nombreOtorgante) &&
        Objects.equals(this.tipoCredito, consultasRCEInner.tipoCredito) &&
        Objects.equals(this.importeCredito, consultasRCEInner.importeCredito) &&
        Objects.equals(this.claveUnidadMonetaria, consultasRCEInner.claveUnidadMonetaria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fechaConsulta, nombreOtorgante, tipoCredito, importeCredito, claveUnidadMonetaria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsultasRCEInner {\n");
    
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    nombreOtorgante: ").append(toIndentedString(nombreOtorgante)).append("\n");
    sb.append("    tipoCredito: ").append(toIndentedString(tipoCredito)).append("\n");
    sb.append("    importeCredito: ").append(toIndentedString(importeCredito)).append("\n");
    sb.append("    claveUnidadMonetaria: ").append(toIndentedString(claveUnidadMonetaria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
