/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.
 */
@ApiModel(description = "El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class CreditoPMInner {
  @SerializedName("RFC")
  private String RFC = null;

  @SerializedName("nombreOtorgante")
  private String nombreOtorgante = null;

  @SerializedName("tipoContrato")
  private Integer tipoContrato = null;

  @SerializedName("numCuenta")
  private String numCuenta = null;

  @SerializedName("periodoAct")
  private String periodoAct = null;

  @SerializedName("cveTipoNegocio")
  private CatalogoTipoNegocio cveTipoNegocio = null;

  @SerializedName("DescTipoNegocio")
  private String descTipoNegocio = null;

  @SerializedName("saldoInicial")
  private Integer saldoInicial = null;

  @SerializedName("cveMoneda")
  private String cveMoneda = null;

  @SerializedName("plazo")
  private Integer plazo = null;

  @SerializedName("clavesObservacion")
  private String clavesObservacion = null;

  @SerializedName("fechaApertura")
  private String fechaApertura = null;

  @SerializedName("CanPagoEfectivo")
  private Integer canPagoEfectivo = null;

  @SerializedName("CanQuita")
  private Integer canQuita = null;

  @SerializedName("CanDuracionPago")
  private Integer canDuracionPago = null;

  @SerializedName("CanQuebrantoCastigo")
  private Integer canQuebrantoCastigo = null;

  @SerializedName("historicoPago")
  private String historicoPago = null;

  @SerializedName("registroImpugnado")
  private String registroImpugnado = null;

  @SerializedName("saldoTotal")
  private Integer saldoTotal = null;

  @SerializedName("vigente")
  private Integer vigente = null;

  @SerializedName("saldoVencido")
  private Integer saldoVencido = null;

  @SerializedName("saldoVencido29dias")
  private Integer saldoVencido29dias = null;

  @SerializedName("saldoVencido59dias")
  private Float saldoVencido59dias = null;

  @SerializedName("saldoVencido89dias")
  private Integer saldoVencido89dias = null;

  @SerializedName("saldoVencido119dias")
  private Float saldoVencido119dias = null;

  @SerializedName("saldoVencido179dias")
  private Integer saldoVencido179dias = null;

  @SerializedName("saldoVencido180MasDias")
  private Integer saldoVencido180MasDias = null;

  @SerializedName("atrasoMayor")
  private Integer atrasoMayor = null;

  @SerializedName("origen")
  private String origen = null;

  @SerializedName("estatusCredito")
  private String estatusCredito = null;

  @SerializedName("DescTipoContrato")
  private CatalogoTipoContrato descTipoContrato = null;

  public CreditoPMInner RFC(String RFC) {
    this.RFC = RFC;
    return this;
  }

   /**
   * Get RFC
   * @return RFC
  **/
  @ApiModelProperty(example = "ADS990201AN1")
  public String getRFC() {
    return RFC;
  }

  public void setRFC(String RFC) {
    this.RFC = RFC;
  }

  public CreditoPMInner nombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
    return this;
  }

   /**
   * Contiene el Nombre del Otorgante de Crédito que reporto el Crédito. Ver Tabla: Tipo de Negocio. &lt;br&gt;Nota: Este elemento solo es reportado para reporte de crédito especial.
   * @return nombreOtorgante
  **/
  @ApiModelProperty(example = "Banco Uno S.A. de C.V.")
  public String getNombreOtorgante() {
    return nombreOtorgante;
  }

  public void setNombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
  }

  public CreditoPMInner tipoContrato(Integer tipoContrato) {
    this.tipoContrato = tipoContrato;
    return this;
  }

   /**
   * Número de contrato.
   * @return tipoContrato
  **/
  @ApiModelProperty(example = "2500303093007")
  public Integer getTipoContrato() {
    return tipoContrato;
  }

  public void setTipoContrato(Integer tipoContrato) {
    this.tipoContrato = tipoContrato;
  }

  public CreditoPMInner numCuenta(String numCuenta) {
    this.numCuenta = numCuenta;
    return this;
  }

   /**
   * Número de cuenta.
   * @return numCuenta
  **/
  @ApiModelProperty(example = "376728332072100")
  public String getNumCuenta() {
    return numCuenta;
  }

  public void setNumCuenta(String numCuenta) {
    this.numCuenta = numCuenta;
  }

  public CreditoPMInner periodoAct(String periodoAct) {
    this.periodoAct = periodoAct;
    return this;
  }

   /**
   * Fecha de periodo actual, en el formato especificado (por defecto yyyy-MM).
   * @return periodoAct
  **/
  @ApiModelProperty(example = "2016-11")
  public String getPeriodoAct() {
    return periodoAct;
  }

  public void setPeriodoAct(String periodoAct) {
    this.periodoAct = periodoAct;
  }

  public CreditoPMInner cveTipoNegocio(CatalogoTipoNegocio cveTipoNegocio) {
    this.cveTipoNegocio = cveTipoNegocio;
    return this;
  }

   /**
   * Get cveTipoNegocio
   * @return cveTipoNegocio
  **/
  @ApiModelProperty()
  public CatalogoTipoNegocio getCveTipoNegocio() {
    return cveTipoNegocio;
  }

  public void setCveTipoNegocio(CatalogoTipoNegocio cveTipoNegocio) {
    this.cveTipoNegocio = cveTipoNegocio;
  }

  public CreditoPMInner descTipoNegocio(String descTipoNegocio) {
    this.descTipoNegocio = descTipoNegocio;
    return this;
  }

   /**
   * Get descTipoNegocio
   * @return descTipoNegocio
  **/
  @ApiModelProperty(example = "BANCOS")
  public String getDescTipoNegocio() {
    return descTipoNegocio;
  }

  public void setDescTipoNegocio(String descTipoNegocio) {
    this.descTipoNegocio = descTipoNegocio;
  }

  public CreditoPMInner saldoInicial(Integer saldoInicial) {
    this.saldoInicial = saldoInicial;
    return this;
  }

   /**
   * Saldo inicial del crédito.
   * @return saldoInicial
  **/
  @ApiModelProperty(example = "2000")
  public Integer getSaldoInicial() {
    return saldoInicial;
  }

  public void setSaldoInicial(Integer saldoInicial) {
    this.saldoInicial = saldoInicial;
  }

  public CreditoPMInner cveMoneda(String cveMoneda) {
    this.cveMoneda = cveMoneda;
    return this;
  }

   /**
   * Get cveMoneda
   * @return cveMoneda
  **/
  @ApiModelProperty()
  public String getCveMoneda() {
    return cveMoneda;
  }

  public void setCveMoneda(String cveMoneda) {
    this.cveMoneda = cveMoneda;
  }

  public CreditoPMInner plazo(Integer plazo) {
    this.plazo = plazo;
    return this;
  }

   /**
   * Término en el que se pactó el crédito. Deberá reportarse en días.
   * @return plazo
  **/
  @ApiModelProperty(example = "90")
  public Integer getPlazo() {
    return plazo;
  }

  public void setPlazo(Integer plazo) {
    this.plazo = plazo;
  }

  public CreditoPMInner clavesObservacion(String clavesObservacion) {
    this.clavesObservacion = clavesObservacion;
    return this;
  }

   /**
   * Get clavesObservacion
   * @return clavesObservacion
  **/
  @ApiModelProperty()
  public String getClavesObservacion() {
    return clavesObservacion;
  }

  public void setClavesObservacion(String clavesObservacion) {
    this.clavesObservacion = clavesObservacion;
  }

  public CreditoPMInner fechaApertura(String fechaApertura) {
    this.fechaApertura = fechaApertura;
    return this;
  }

   /**
   * Fecha de apertura del crédito, en el formato especificado (por defecto yyyy-MM-dd).
   * @return fechaApertura
  **/
  @ApiModelProperty(example = "2016-02-19")
  public String getFechaApertura() {
    return fechaApertura;
  }

  public void setFechaApertura(String fechaApertura) {
    this.fechaApertura = fechaApertura;
  }

  public CreditoPMInner canPagoEfectivo(Integer canPagoEfectivo) {
    this.canPagoEfectivo = canPagoEfectivo;
    return this;
  }

   /**
   * Get canPagoEfectivo
   * @return canPagoEfectivo
  **/
  @ApiModelProperty(example = "2199920")
  public Integer getCanPagoEfectivo() {
    return canPagoEfectivo;
  }

  public void setCanPagoEfectivo(Integer canPagoEfectivo) {
    this.canPagoEfectivo = canPagoEfectivo;
  }

  public CreditoPMInner canQuita(Integer canQuita) {
    this.canQuita = canQuita;
    return this;
  }

   /**
   * Get canQuita
   * @return canQuita
  **/
  @ApiModelProperty(example = "0")
  public Integer getCanQuita() {
    return canQuita;
  }

  public void setCanQuita(Integer canQuita) {
    this.canQuita = canQuita;
  }

  public CreditoPMInner canDuracionPago(Integer canDuracionPago) {
    this.canDuracionPago = canDuracionPago;
    return this;
  }

   /**
   * Get canDuracionPago
   * @return canDuracionPago
  **/
  @ApiModelProperty(example = "0")
  public Integer getCanDuracionPago() {
    return canDuracionPago;
  }

  public void setCanDuracionPago(Integer canDuracionPago) {
    this.canDuracionPago = canDuracionPago;
  }

  public CreditoPMInner canQuebrantoCastigo(Integer canQuebrantoCastigo) {
    this.canQuebrantoCastigo = canQuebrantoCastigo;
    return this;
  }

   /**
   * Get canQuebrantoCastigo
   * @return canQuebrantoCastigo
  **/
  @ApiModelProperty(example = "0")
  public Integer getCanQuebrantoCastigo() {
    return canQuebrantoCastigo;
  }

  public void setCanQuebrantoCastigo(Integer canQuebrantoCastigo) {
    this.canQuebrantoCastigo = canQuebrantoCastigo;
  }

  public CreditoPMInner historicoPago(String historicoPago) {
    this.historicoPago = historicoPago;
    return this;
  }

   /**
   * Patrón histórico de pagos
   * @return historicoPago
  **/
  @ApiModelProperty(example = "111111111111------")
  public String getHistoricoPago() {
    return historicoPago;
  }

  public void setHistoricoPago(String historicoPago) {
    this.historicoPago = historicoPago;
  }

  public CreditoPMInner registroImpugnado(String registroImpugnado) {
    this.registroImpugnado = registroImpugnado;
    return this;
  }

   /**
   * Si contiene RI, el registro está impugnado.
   * @return registroImpugnado
  **/
  @ApiModelProperty(example = "RI")
  public String getRegistroImpugnado() {
    return registroImpugnado;
  }

  public void setRegistroImpugnado(String registroImpugnado) {
    this.registroImpugnado = registroImpugnado;
  }

  public CreditoPMInner saldoTotal(Integer saldoTotal) {
    this.saldoTotal = saldoTotal;
    return this;
  }

   /**
   * Saldo total del crédito.
   * @return saldoTotal
  **/
  @ApiModelProperty(example = "2000")
  public Integer getSaldoTotal() {
    return saldoTotal;
  }

  public void setSaldoTotal(Integer saldoTotal) {
    this.saldoTotal = saldoTotal;
  }

  public CreditoPMInner vigente(Integer vigente) {
    this.vigente = vigente;
    return this;
  }

   /**
   * Monto Vigente. Sólo con créditos abiertos.
   * @return vigente
  **/
  @ApiModelProperty(example = "546780")
  public Integer getVigente() {
    return vigente;
  }

  public void setVigente(Integer vigente) {
    this.vigente = vigente;
  }

  public CreditoPMInner saldoVencido(Integer saldoVencido) {
    this.saldoVencido = saldoVencido;
    return this;
  }

   /**
   * Get saldoVencido
   * @return saldoVencido
  **/
  @ApiModelProperty(example = "0")
  public Integer getSaldoVencido() {
    return saldoVencido;
  }

  public void setSaldoVencido(Integer saldoVencido) {
    this.saldoVencido = saldoVencido;
  }

  public CreditoPMInner saldoVencido29dias(Integer saldoVencido29dias) {
    this.saldoVencido29dias = saldoVencido29dias;
    return this;
  }

   /**
   * Vencido de 1 a 29 días. Sólo con créditos abiertos.
   * @return saldoVencido29dias
  **/
  @ApiModelProperty(example = "0")
  public Integer getSaldoVencido29dias() {
    return saldoVencido29dias;
  }

  public void setSaldoVencido29dias(Integer saldoVencido29dias) {
    this.saldoVencido29dias = saldoVencido29dias;
  }

  public CreditoPMInner saldoVencido59dias(Float saldoVencido59dias) {
    this.saldoVencido59dias = saldoVencido59dias;
    return this;
  }

   /**
   * Vencido de 30 a 59 días. Sólo con créditos abiertos.
   * @return saldoVencido59dias
  **/
  @ApiModelProperty(example = "0")
  public Float getSaldoVencido59dias() {
    return saldoVencido59dias;
  }

  public void setSaldoVencido59dias(Float saldoVencido59dias) {
    this.saldoVencido59dias = saldoVencido59dias;
  }

  public CreditoPMInner saldoVencido89dias(Integer saldoVencido89dias) {
    this.saldoVencido89dias = saldoVencido89dias;
    return this;
  }

   /**
   * Vencido de 60 a 89 días. Sólo con créditos abiertos.
   * @return saldoVencido89dias
  **/
  @ApiModelProperty(example = "0")
  public Integer getSaldoVencido89dias() {
    return saldoVencido89dias;
  }

  public void setSaldoVencido89dias(Integer saldoVencido89dias) {
    this.saldoVencido89dias = saldoVencido89dias;
  }

  public CreditoPMInner saldoVencido119dias(Float saldoVencido119dias) {
    this.saldoVencido119dias = saldoVencido119dias;
    return this;
  }

   /**
   * Vencido de 90 a 119 días. Sólo con créditos abiertos.
   * @return saldoVencido119dias
  **/
  @ApiModelProperty(example = "0")
  public Float getSaldoVencido119dias() {
    return saldoVencido119dias;
  }

  public void setSaldoVencido119dias(Float saldoVencido119dias) {
    this.saldoVencido119dias = saldoVencido119dias;
  }

  public CreditoPMInner saldoVencido179dias(Integer saldoVencido179dias) {
    this.saldoVencido179dias = saldoVencido179dias;
    return this;
  }

   /**
   * Vencido de 120 a 179 días. Sólo con créditos abiertos.
   * @return saldoVencido179dias
  **/
  @ApiModelProperty(example = "0")
  public Integer getSaldoVencido179dias() {
    return saldoVencido179dias;
  }

  public void setSaldoVencido179dias(Integer saldoVencido179dias) {
    this.saldoVencido179dias = saldoVencido179dias;
  }

  public CreditoPMInner saldoVencido180MasDias(Integer saldoVencido180MasDias) {
    this.saldoVencido180MasDias = saldoVencido180MasDias;
    return this;
  }

   /**
   * Vencido 180 días a más. Sólo con créditos abiertos.
   * @return saldoVencido180MasDias
  **/
  @ApiModelProperty(example = "1500")
  public Integer getSaldoVencido180MasDias() {
    return saldoVencido180MasDias;
  }

  public void setSaldoVencido180MasDias(Integer saldoVencido180MasDias) {
    this.saldoVencido180MasDias = saldoVencido180MasDias;
  }

  public CreditoPMInner atrasoMayor(Integer atrasoMayor) {
    this.atrasoMayor = atrasoMayor;
    return this;
  }

   /**
   * Muestra la cantidad exacta de días de atraso cuando se reportan montos con vencimiento.
   * @return atrasoMayor
  **/
  @ApiModelProperty(example = "10")
  public Integer getAtrasoMayor() {
    return atrasoMayor;
  }

  public void setAtrasoMayor(Integer atrasoMayor) {
    this.atrasoMayor = atrasoMayor;
  }

  public CreditoPMInner origen(String origen) {
    this.origen = origen;
    return this;
  }

   /**
   * Get origen
   * @return origen
  **/
  @ApiModelProperty(example = "CC")
  public String getOrigen() {
    return origen;
  }

  public void setOrigen(String origen) {
    this.origen = origen;
  }

  public CreditoPMInner estatusCredito(String estatusCredito) {
    this.estatusCredito = estatusCredito;
    return this;
  }

   /**
   * Get estatusCredito
   * @return estatusCredito
  **/
  @ApiModelProperty(example = "ABIERTO")
  public String getEstatusCredito() {
    return estatusCredito;
  }

  public void setEstatusCredito(String estatusCredito) {
    this.estatusCredito = estatusCredito;
  }

  public CreditoPMInner descTipoContrato(CatalogoTipoContrato descTipoContrato) {
    this.descTipoContrato = descTipoContrato;
    return this;
  }

   /**
   * Get descTipoContrato
   * @return descTipoContrato
  **/
  @ApiModelProperty()
  public CatalogoTipoContrato getDescTipoContrato() {
    return descTipoContrato;
  }

  public void setDescTipoContrato(CatalogoTipoContrato descTipoContrato) {
    this.descTipoContrato = descTipoContrato;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditoPMInner creditoPMInner = (CreditoPMInner) o;
    return Objects.equals(this.RFC, creditoPMInner.RFC) &&
        Objects.equals(this.nombreOtorgante, creditoPMInner.nombreOtorgante) &&
        Objects.equals(this.tipoContrato, creditoPMInner.tipoContrato) &&
        Objects.equals(this.numCuenta, creditoPMInner.numCuenta) &&
        Objects.equals(this.periodoAct, creditoPMInner.periodoAct) &&
        Objects.equals(this.cveTipoNegocio, creditoPMInner.cveTipoNegocio) &&
        Objects.equals(this.descTipoNegocio, creditoPMInner.descTipoNegocio) &&
        Objects.equals(this.saldoInicial, creditoPMInner.saldoInicial) &&
        Objects.equals(this.cveMoneda, creditoPMInner.cveMoneda) &&
        Objects.equals(this.plazo, creditoPMInner.plazo) &&
        Objects.equals(this.clavesObservacion, creditoPMInner.clavesObservacion) &&
        Objects.equals(this.fechaApertura, creditoPMInner.fechaApertura) &&
        Objects.equals(this.canPagoEfectivo, creditoPMInner.canPagoEfectivo) &&
        Objects.equals(this.canQuita, creditoPMInner.canQuita) &&
        Objects.equals(this.canDuracionPago, creditoPMInner.canDuracionPago) &&
        Objects.equals(this.canQuebrantoCastigo, creditoPMInner.canQuebrantoCastigo) &&
        Objects.equals(this.historicoPago, creditoPMInner.historicoPago) &&
        Objects.equals(this.registroImpugnado, creditoPMInner.registroImpugnado) &&
        Objects.equals(this.saldoTotal, creditoPMInner.saldoTotal) &&
        Objects.equals(this.vigente, creditoPMInner.vigente) &&
        Objects.equals(this.saldoVencido, creditoPMInner.saldoVencido) &&
        Objects.equals(this.saldoVencido29dias, creditoPMInner.saldoVencido29dias) &&
        Objects.equals(this.saldoVencido59dias, creditoPMInner.saldoVencido59dias) &&
        Objects.equals(this.saldoVencido89dias, creditoPMInner.saldoVencido89dias) &&
        Objects.equals(this.saldoVencido119dias, creditoPMInner.saldoVencido119dias) &&
        Objects.equals(this.saldoVencido179dias, creditoPMInner.saldoVencido179dias) &&
        Objects.equals(this.saldoVencido180MasDias, creditoPMInner.saldoVencido180MasDias) &&
        Objects.equals(this.atrasoMayor, creditoPMInner.atrasoMayor) &&
        Objects.equals(this.origen, creditoPMInner.origen) &&
        Objects.equals(this.estatusCredito, creditoPMInner.estatusCredito) &&
        Objects.equals(this.descTipoContrato, creditoPMInner.descTipoContrato);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RFC, nombreOtorgante, tipoContrato, numCuenta, periodoAct, cveTipoNegocio, descTipoNegocio, saldoInicial, cveMoneda, plazo, clavesObservacion, fechaApertura, canPagoEfectivo, canQuita, canDuracionPago, canQuebrantoCastigo, historicoPago, registroImpugnado, saldoTotal, vigente, saldoVencido, saldoVencido29dias, saldoVencido59dias, saldoVencido89dias, saldoVencido119dias, saldoVencido179dias, saldoVencido180MasDias, atrasoMayor, origen, estatusCredito, descTipoContrato);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditoPMInner {\n");
    
    sb.append("    RFC: ").append(toIndentedString(RFC)).append("\n");
    sb.append("    nombreOtorgante: ").append(toIndentedString(nombreOtorgante)).append("\n");
    sb.append("    tipoContrato: ").append(toIndentedString(tipoContrato)).append("\n");
    sb.append("    numCuenta: ").append(toIndentedString(numCuenta)).append("\n");
    sb.append("    periodoAct: ").append(toIndentedString(periodoAct)).append("\n");
    sb.append("    cveTipoNegocio: ").append(toIndentedString(cveTipoNegocio)).append("\n");
    sb.append("    descTipoNegocio: ").append(toIndentedString(descTipoNegocio)).append("\n");
    sb.append("    saldoInicial: ").append(toIndentedString(saldoInicial)).append("\n");
    sb.append("    cveMoneda: ").append(toIndentedString(cveMoneda)).append("\n");
    sb.append("    plazo: ").append(toIndentedString(plazo)).append("\n");
    sb.append("    clavesObservacion: ").append(toIndentedString(clavesObservacion)).append("\n");
    sb.append("    fechaApertura: ").append(toIndentedString(fechaApertura)).append("\n");
    sb.append("    canPagoEfectivo: ").append(toIndentedString(canPagoEfectivo)).append("\n");
    sb.append("    canQuita: ").append(toIndentedString(canQuita)).append("\n");
    sb.append("    canDuracionPago: ").append(toIndentedString(canDuracionPago)).append("\n");
    sb.append("    canQuebrantoCastigo: ").append(toIndentedString(canQuebrantoCastigo)).append("\n");
    sb.append("    historicoPago: ").append(toIndentedString(historicoPago)).append("\n");
    sb.append("    registroImpugnado: ").append(toIndentedString(registroImpugnado)).append("\n");
    sb.append("    saldoTotal: ").append(toIndentedString(saldoTotal)).append("\n");
    sb.append("    vigente: ").append(toIndentedString(vigente)).append("\n");
    sb.append("    saldoVencido: ").append(toIndentedString(saldoVencido)).append("\n");
    sb.append("    saldoVencido29dias: ").append(toIndentedString(saldoVencido29dias)).append("\n");
    sb.append("    saldoVencido59dias: ").append(toIndentedString(saldoVencido59dias)).append("\n");
    sb.append("    saldoVencido89dias: ").append(toIndentedString(saldoVencido89dias)).append("\n");
    sb.append("    saldoVencido119dias: ").append(toIndentedString(saldoVencido119dias)).append("\n");
    sb.append("    saldoVencido179dias: ").append(toIndentedString(saldoVencido179dias)).append("\n");
    sb.append("    saldoVencido180MasDias: ").append(toIndentedString(saldoVencido180MasDias)).append("\n");
    sb.append("    atrasoMayor: ").append(toIndentedString(atrasoMayor)).append("\n");
    sb.append("    origen: ").append(toIndentedString(origen)).append("\n");
    sb.append("    estatusCredito: ").append(toIndentedString(estatusCredito)).append("\n");
    sb.append("    descTipoContrato: ").append(toIndentedString(descTipoContrato)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
