/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.ArrayList;
import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Creditos
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class Creditos {
  @SerializedName("cuentasFinancieras")
  private ArrayList<CreditoPMInner> cuentasFinancieras = null;

  @SerializedName("cuentasComerciales")
  private CuentasComerciales cuentasComerciales = null;

  public Creditos cuentasFinancieras(ArrayList<CreditoPMInner> cuentasFinancieras) {
    this.cuentasFinancieras = cuentasFinancieras;
    return this;
  }

   /**
   * Get cuentasFinancieras
   * @return cuentasFinancieras
  **/
  @ApiModelProperty()
  public ArrayList<CreditoPMInner> getCuentasFinancieras() {
    return cuentasFinancieras;
  }

  public void setCuentasFinancieras(ArrayList<CreditoPMInner> cuentasFinancieras) {
    this.cuentasFinancieras = cuentasFinancieras;
  }

  public Creditos cuentasComerciales(CuentasComerciales cuentasComerciales) {
    this.cuentasComerciales = cuentasComerciales;
    return this;
  }

   /**
   * Get cuentasComerciales
   * @return cuentasComerciales
  **/
  @ApiModelProperty()
  public CuentasComerciales getCuentasComerciales() {
    return cuentasComerciales;
  }

  public void setCuentasComerciales(CuentasComerciales cuentasComerciales) {
    this.cuentasComerciales = cuentasComerciales;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Creditos creditos = (Creditos) o;
    return Objects.equals(this.cuentasFinancieras, creditos.cuentasFinancieras) &&
        Objects.equals(this.cuentasComerciales, creditos.cuentasComerciales);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cuentasFinancieras, cuentasComerciales);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Creditos {\n");
    
    sb.append("    cuentasFinancieras: ").append(toIndentedString(cuentasFinancieras)).append("\n");
    sb.append("    cuentasComerciales: ").append(toIndentedString(cuentasComerciales)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
