/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.
 */
@ApiModel(description = "El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class CreditoInner {
  @SerializedName("RFC")
  private String RFC = null;

  @SerializedName("nombreOtorgante")
  private String nombreOtorgante = null;

  @SerializedName("contrato")
  private Integer contrato = null;

  @SerializedName("saldoInicial")
  private Integer saldoInicial = null;

  @SerializedName("saldoTotal")
  private Integer saldoTotal = null;

  @SerializedName("moneda")
  private String moneda = null;

  @SerializedName("fechaApertura")
  private String fechaApertura = null;

  @SerializedName("plazo")
  private Integer plazo = null;

  @SerializedName("clavesObservacion")
  private String clavesObservacion = null;

  @SerializedName("tipoCredito")
  private String tipoCredito = null;

  @SerializedName("vigente")
  private Integer vigente = null;

  @SerializedName("29dias")
  private Integer _29dias = null;

  @SerializedName("59dias")
  private Float _59dias = null;

  @SerializedName("89dias")
  private Integer _89dias = null;

  @SerializedName("119dias")
  private Float _119dias = null;

  @SerializedName("179dias")
  private Integer _179dias = null;

  @SerializedName("180MasDias")
  private Integer _180MasDias = null;

  @SerializedName("actualizacion")
  private String actualizacion = null;

  @SerializedName("fechaCierre")
  private String fechaCierre = null;

  @SerializedName("pagoEfectivo")
  private Integer pagoEfectivo = null;

  @SerializedName("quita")
  private Integer quita = null;

  @SerializedName("dacionPago")
  private Integer dacionPago = null;

  @SerializedName("quebrantoCastigo")
  private Integer quebrantoCastigo = null;

  @SerializedName("historia")
  private String historia = null;

  @SerializedName("atrasoMayor")
  private Integer atrasoMayor = null;

  @SerializedName("registroImpugnado")
  private String registroImpugnado = null;

  public CreditoInner RFC(String RFC) {
    this.RFC = RFC;
    return this;
  }

   /**
   * Get RFC
   * @return RFC
  **/
  @ApiModelProperty(example = "ADS990201AN1")
  public String getRFC() {
    return RFC;
  }

  public void setRFC(String RFC) {
    this.RFC = RFC;
  }

  public CreditoInner nombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
    return this;
  }

   /**
   * Contiene el Nombre del Otorgante de Crédito que reporto el Crédito. Ver Tabla: Tipo de Negocio. &lt;br&gt;Nota: Este elemento solo es reportado para reporte de crédito especial.
   * @return nombreOtorgante
  **/
  @ApiModelProperty(example = "BANCO")
  public String getNombreOtorgante() {
    return nombreOtorgante;
  }

  public void setNombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
  }

  public CreditoInner contrato(Integer contrato) {
    this.contrato = contrato;
    return this;
  }

   /**
   * Número de contrato.
   * @return contrato
  **/
  @ApiModelProperty(example = "2500303093007")
  public Integer getContrato() {
    return contrato;
  }

  public void setContrato(Integer contrato) {
    this.contrato = contrato;
  }

  public CreditoInner saldoInicial(Integer saldoInicial) {
    this.saldoInicial = saldoInicial;
    return this;
  }

   /**
   * Saldo inicial del crédito.
   * @return saldoInicial
  **/
  @ApiModelProperty(example = "2000")
  public Integer getSaldoInicial() {
    return saldoInicial;
  }

  public void setSaldoInicial(Integer saldoInicial) {
    this.saldoInicial = saldoInicial;
  }

  public CreditoInner saldoTotal(Integer saldoTotal) {
    this.saldoTotal = saldoTotal;
    return this;
  }

   /**
   * Saldo total del crédito.
   * @return saldoTotal
  **/
  @ApiModelProperty(example = "2000")
  public Integer getSaldoTotal() {
    return saldoTotal;
  }

  public void setSaldoTotal(Integer saldoTotal) {
    this.saldoTotal = saldoTotal;
  }

  public CreditoInner moneda(String moneda) {
    this.moneda = moneda;
    return this;
  }

   /**
   * Get moneda
   * @return moneda
  **/
  @ApiModelProperty()
  public String getMoneda() {
    return moneda;
  }

  public void setMoneda(String moneda) {
    this.moneda = moneda;
  }

  public CreditoInner fechaApertura(String fechaApertura) {
    this.fechaApertura = fechaApertura;
    return this;
  }

   /**
   * Fecha de apertura del crédito, en el formato especificado (por defecto yyyy-MM-dd).
   * @return fechaApertura
  **/
  @ApiModelProperty(example = "2016-02-19")
  public String getFechaApertura() {
    return fechaApertura;
  }

  public void setFechaApertura(String fechaApertura) {
    this.fechaApertura = fechaApertura;
  }

  public CreditoInner plazo(Integer plazo) {
    this.plazo = plazo;
    return this;
  }

   /**
   * Término en el que se pactó el crédito. Deberá reportarse en días.
   * @return plazo
  **/
  @ApiModelProperty(example = "90")
  public Integer getPlazo() {
    return plazo;
  }

  public void setPlazo(Integer plazo) {
    this.plazo = plazo;
  }

  public CreditoInner clavesObservacion(String clavesObservacion) {
    this.clavesObservacion = clavesObservacion;
    return this;
  }

   /**
   * Get clavesObservacion
   * @return clavesObservacion
  **/
  @ApiModelProperty()
  public String getClavesObservacion() {
    return clavesObservacion;
  }

  public void setClavesObservacion(String clavesObservacion) {
    this.clavesObservacion = clavesObservacion;
  }

  public CreditoInner tipoCredito(String tipoCredito) {
    this.tipoCredito = tipoCredito;
    return this;
  }

   /**
   * Get tipoCredito
   * @return tipoCredito
  **/
  @ApiModelProperty()
  public String getTipoCredito() {
    return tipoCredito;
  }

  public void setTipoCredito(String tipoCredito) {
    this.tipoCredito = tipoCredito;
  }

  public CreditoInner vigente(Integer vigente) {
    this.vigente = vigente;
    return this;
  }

   /**
   * Monto Vigente. Sólo con créditos abiertos.
   * @return vigente
  **/
  @ApiModelProperty(example = "546780")
  public Integer getVigente() {
    return vigente;
  }

  public void setVigente(Integer vigente) {
    this.vigente = vigente;
  }

  public CreditoInner _29dias(Integer _29dias) {
    this._29dias = _29dias;
    return this;
  }

   /**
   * Vencido de 1 a 29 días. Sólo con créditos abiertos.
   * @return _29dias
  **/
  @ApiModelProperty(example = "0")
  public Integer get29dias() {
    return _29dias;
  }

  public void set29dias(Integer _29dias) {
    this._29dias = _29dias;
  }

  public CreditoInner _59dias(Float _59dias) {
    this._59dias = _59dias;
    return this;
  }

   /**
   * Vencido de 30 a 59 días. Sólo con créditos abiertos.
   * @return _59dias
  **/
  @ApiModelProperty(example = "0")
  public Float get59dias() {
    return _59dias;
  }

  public void set59dias(Float _59dias) {
    this._59dias = _59dias;
  }

  public CreditoInner _89dias(Integer _89dias) {
    this._89dias = _89dias;
    return this;
  }

   /**
   * Vencido de 60 a 89 días. Sólo con créditos abiertos.
   * @return _89dias
  **/
  @ApiModelProperty(example = "0")
  public Integer get89dias() {
    return _89dias;
  }

  public void set89dias(Integer _89dias) {
    this._89dias = _89dias;
  }

  public CreditoInner _119dias(Float _119dias) {
    this._119dias = _119dias;
    return this;
  }

   /**
   * Vencido de 90 a 119 días. Sólo con créditos abiertos.
   * @return _119dias
  **/
  @ApiModelProperty(example = "0")
  public Float get119dias() {
    return _119dias;
  }

  public void set119dias(Float _119dias) {
    this._119dias = _119dias;
  }

  public CreditoInner _179dias(Integer _179dias) {
    this._179dias = _179dias;
    return this;
  }

   /**
   * Vencido de 120 a 179 días. Sólo con créditos abiertos.
   * @return _179dias
  **/
  @ApiModelProperty(example = "0")
  public Integer get179dias() {
    return _179dias;
  }

  public void set179dias(Integer _179dias) {
    this._179dias = _179dias;
  }

  public CreditoInner _180MasDias(Integer _180MasDias) {
    this._180MasDias = _180MasDias;
    return this;
  }

   /**
   * Vencido 180 días a más. Sólo con créditos abiertos.
   * @return _180MasDias
  **/
  @ApiModelProperty(example = "1500")
  public Integer get180MasDias() {
    return _180MasDias;
  }

  public void set180MasDias(Integer _180MasDias) {
    this._180MasDias = _180MasDias;
  }

  public CreditoInner actualizacion(String actualizacion) {
    this.actualizacion = actualizacion;
    return this;
  }

   /**
   * Último periodo de actualización (sólo con créditos abiertos), en el formato especificado (por defecto yyyy-MM).
   * @return actualizacion
  **/
  @ApiModelProperty(example = "2018-20")
  public String getActualizacion() {
    return actualizacion;
  }

  public void setActualizacion(String actualizacion) {
    this.actualizacion = actualizacion;
  }

  public CreditoInner fechaCierre(String fechaCierre) {
    this.fechaCierre = fechaCierre;
    return this;
  }

   /**
   * Fecha de cierre del crédito (sólo con créditos cerrados), en el formato especificado (por defecto yyyy-MM-dd).
   * @return fechaCierre
  **/
  @ApiModelProperty(example = "2018-02-20")
  public String getFechaCierre() {
    return fechaCierre;
  }

  public void setFechaCierre(String fechaCierre) {
    this.fechaCierre = fechaCierre;
  }

  public CreditoInner pagoEfectivo(Integer pagoEfectivo) {
    this.pagoEfectivo = pagoEfectivo;
    return this;
  }

   /**
   * Pago efectuado al cierre del crédito. Sólo con créditos cerrados.
   * @return pagoEfectivo
  **/
  @ApiModelProperty(example = "579809")
  public Integer getPagoEfectivo() {
    return pagoEfectivo;
  }

  public void setPagoEfectivo(Integer pagoEfectivo) {
    this.pagoEfectivo = pagoEfectivo;
  }

  public CreditoInner quita(Integer quita) {
    this.quita = quita;
    return this;
  }

   /**
   * Monto de la quita. Solo con créditos cerrados.
   * @return quita
  **/
  @ApiModelProperty(example = "5789")
  public Integer getQuita() {
    return quita;
  }

  public void setQuita(Integer quita) {
    this.quita = quita;
  }

  public CreditoInner dacionPago(Integer dacionPago) {
    this.dacionPago = dacionPago;
    return this;
  }

   /**
   * Monto de la dación. Solo con créditos cerrados.
   * @return dacionPago
  **/
  @ApiModelProperty(example = "0")
  public Integer getDacionPago() {
    return dacionPago;
  }

  public void setDacionPago(Integer dacionPago) {
    this.dacionPago = dacionPago;
  }

  public CreditoInner quebrantoCastigo(Integer quebrantoCastigo) {
    this.quebrantoCastigo = quebrantoCastigo;
    return this;
  }

   /**
   * Monto del quebranto efectuado. Solo con créditos cerrados.
   * @return quebrantoCastigo
  **/
  @ApiModelProperty(example = "0")
  public Integer getQuebrantoCastigo() {
    return quebrantoCastigo;
  }

  public void setQuebrantoCastigo(Integer quebrantoCastigo) {
    this.quebrantoCastigo = quebrantoCastigo;
  }

  public CreditoInner historia(String historia) {
    this.historia = historia;
    return this;
  }

   /**
   * Patrón histórico de pagos
   * @return historia
  **/
  @ApiModelProperty(example = "111111111111------")
  public String getHistoria() {
    return historia;
  }

  public void setHistoria(String historia) {
    this.historia = historia;
  }

  public CreditoInner atrasoMayor(Integer atrasoMayor) {
    this.atrasoMayor = atrasoMayor;
    return this;
  }

   /**
   * Muestra la cantidad exacta de días de atraso cuando se reportan montos con vencimiento.
   * @return atrasoMayor
  **/
  @ApiModelProperty(example = "10")
  public Integer getAtrasoMayor() {
    return atrasoMayor;
  }

  public void setAtrasoMayor(Integer atrasoMayor) {
    this.atrasoMayor = atrasoMayor;
  }

  public CreditoInner registroImpugnado(String registroImpugnado) {
    this.registroImpugnado = registroImpugnado;
    return this;
  }

   /**
   * Si contiene RI, el registro está impugnado.
   * @return registroImpugnado
  **/
  @ApiModelProperty(example = "RI")
  public String getRegistroImpugnado() {
    return registroImpugnado;
  }

  public void setRegistroImpugnado(String registroImpugnado) {
    this.registroImpugnado = registroImpugnado;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditoInner creditoInner = (CreditoInner) o;
    return Objects.equals(this.RFC, creditoInner.RFC) &&
        Objects.equals(this.nombreOtorgante, creditoInner.nombreOtorgante) &&
        Objects.equals(this.contrato, creditoInner.contrato) &&
        Objects.equals(this.saldoInicial, creditoInner.saldoInicial) &&
        Objects.equals(this.saldoTotal, creditoInner.saldoTotal) &&
        Objects.equals(this.moneda, creditoInner.moneda) &&
        Objects.equals(this.fechaApertura, creditoInner.fechaApertura) &&
        Objects.equals(this.plazo, creditoInner.plazo) &&
        Objects.equals(this.clavesObservacion, creditoInner.clavesObservacion) &&
        Objects.equals(this.tipoCredito, creditoInner.tipoCredito) &&
        Objects.equals(this.vigente, creditoInner.vigente) &&
        Objects.equals(this._29dias, creditoInner._29dias) &&
        Objects.equals(this._59dias, creditoInner._59dias) &&
        Objects.equals(this._89dias, creditoInner._89dias) &&
        Objects.equals(this._119dias, creditoInner._119dias) &&
        Objects.equals(this._179dias, creditoInner._179dias) &&
        Objects.equals(this._180MasDias, creditoInner._180MasDias) &&
        Objects.equals(this.actualizacion, creditoInner.actualizacion) &&
        Objects.equals(this.fechaCierre, creditoInner.fechaCierre) &&
        Objects.equals(this.pagoEfectivo, creditoInner.pagoEfectivo) &&
        Objects.equals(this.quita, creditoInner.quita) &&
        Objects.equals(this.dacionPago, creditoInner.dacionPago) &&
        Objects.equals(this.quebrantoCastigo, creditoInner.quebrantoCastigo) &&
        Objects.equals(this.historia, creditoInner.historia) &&
        Objects.equals(this.atrasoMayor, creditoInner.atrasoMayor) &&
        Objects.equals(this.registroImpugnado, creditoInner.registroImpugnado);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RFC, nombreOtorgante, contrato, saldoInicial, saldoTotal, moneda, fechaApertura, plazo, clavesObservacion, tipoCredito, vigente, _29dias, _59dias, _89dias, _119dias, _179dias, _180MasDias, actualizacion, fechaCierre, pagoEfectivo, quita, dacionPago, quebrantoCastigo, historia, atrasoMayor, registroImpugnado);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditoInner {\n");
    
    sb.append("    RFC: ").append(toIndentedString(RFC)).append("\n");
    sb.append("    nombreOtorgante: ").append(toIndentedString(nombreOtorgante)).append("\n");
    sb.append("    contrato: ").append(toIndentedString(contrato)).append("\n");
    sb.append("    saldoInicial: ").append(toIndentedString(saldoInicial)).append("\n");
    sb.append("    saldoTotal: ").append(toIndentedString(saldoTotal)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    fechaApertura: ").append(toIndentedString(fechaApertura)).append("\n");
    sb.append("    plazo: ").append(toIndentedString(plazo)).append("\n");
    sb.append("    clavesObservacion: ").append(toIndentedString(clavesObservacion)).append("\n");
    sb.append("    tipoCredito: ").append(toIndentedString(tipoCredito)).append("\n");
    sb.append("    vigente: ").append(toIndentedString(vigente)).append("\n");
    sb.append("    _29dias: ").append(toIndentedString(_29dias)).append("\n");
    sb.append("    _59dias: ").append(toIndentedString(_59dias)).append("\n");
    sb.append("    _89dias: ").append(toIndentedString(_89dias)).append("\n");
    sb.append("    _119dias: ").append(toIndentedString(_119dias)).append("\n");
    sb.append("    _179dias: ").append(toIndentedString(_179dias)).append("\n");
    sb.append("    _180MasDias: ").append(toIndentedString(_180MasDias)).append("\n");
    sb.append("    actualizacion: ").append(toIndentedString(actualizacion)).append("\n");
    sb.append("    fechaCierre: ").append(toIndentedString(fechaCierre)).append("\n");
    sb.append("    pagoEfectivo: ").append(toIndentedString(pagoEfectivo)).append("\n");
    sb.append("    quita: ").append(toIndentedString(quita)).append("\n");
    sb.append("    dacionPago: ").append(toIndentedString(dacionPago)).append("\n");
    sb.append("    quebrantoCastigo: ").append(toIndentedString(quebrantoCastigo)).append("\n");
    sb.append("    historia: ").append(toIndentedString(historia)).append("\n");
    sb.append("    atrasoMayor: ").append(toIndentedString(atrasoMayor)).append("\n");
    sb.append("    registroImpugnado: ").append(toIndentedString(registroImpugnado)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
