/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.
 */
@ApiModel(description = "El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class CuentasComercialesInner {
  @SerializedName("RFC")
  private String RFC = null;

  @SerializedName("nombreOtorgante")
  private String nombreOtorgante = null;

  @SerializedName("moneda")
  private String moneda = null;

  @SerializedName("vigente")
  private Integer vigente = null;

  @SerializedName("saldoTotal")
  private Integer saldoTotal = null;

  @SerializedName("29dias")
  private Integer _29dias = null;

  @SerializedName("59dias")
  private Float _59dias = null;

  @SerializedName("89dias")
  private Integer _89dias = null;

  @SerializedName("119dias")
  private Float _119dias = null;

  @SerializedName("179dias")
  private Integer _179dias = null;

  @SerializedName("180MasDias")
  private Integer _180MasDias = null;

  @SerializedName("actualizacion")
  private String actualizacion = null;

  @SerializedName("historia")
  private String historia = null;

  @SerializedName("atrasoMayor")
  private Integer atrasoMayor = null;

  public CuentasComercialesInner RFC(String RFC) {
    this.RFC = RFC;
    return this;
  }

   /**
   * Get RFC
   * @return RFC
  **/
  @ApiModelProperty(example = "ADS990201AN1")
  public String getRFC() {
    return RFC;
  }

  public void setRFC(String RFC) {
    this.RFC = RFC;
  }

  public CuentasComercialesInner nombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
    return this;
  }

   /**
   * Contiene el Nombre del Otorgante de Crédito que reporto el Crédito. Ver Tabla: Tipo de Negocio. &lt;br&gt;Nota: Este elemento solo es reportado para reporte de crédito especial.
   * @return nombreOtorgante
  **/
  @ApiModelProperty(example = "BANCO")
  public String getNombreOtorgante() {
    return nombreOtorgante;
  }

  public void setNombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
  }

  public CuentasComercialesInner moneda(String moneda) {
    this.moneda = moneda;
    return this;
  }

   /**
   * Get moneda
   * @return moneda
  **/
  @ApiModelProperty()
  public String getMoneda() {
    return moneda;
  }

  public void setMoneda(String moneda) {
    this.moneda = moneda;
  }

  public CuentasComercialesInner vigente(Integer vigente) {
    this.vigente = vigente;
    return this;
  }

   /**
   * Monto Vigente. Sólo con créditos abiertos.
   * @return vigente
  **/
  @ApiModelProperty(example = "546780")
  public Integer getVigente() {
    return vigente;
  }

  public void setVigente(Integer vigente) {
    this.vigente = vigente;
  }

  public CuentasComercialesInner saldoTotal(Integer saldoTotal) {
    this.saldoTotal = saldoTotal;
    return this;
  }

   /**
   * Saldo total del crédito.
   * @return saldoTotal
  **/
  @ApiModelProperty(example = "2000")
  public Integer getSaldoTotal() {
    return saldoTotal;
  }

  public void setSaldoTotal(Integer saldoTotal) {
    this.saldoTotal = saldoTotal;
  }

  public CuentasComercialesInner _29dias(Integer _29dias) {
    this._29dias = _29dias;
    return this;
  }

   /**
   * Vencido de 1 a 29 días. Sólo con créditos abiertos.
   * @return _29dias
  **/
  @ApiModelProperty(example = "0")
  public Integer get29dias() {
    return _29dias;
  }

  public void set29dias(Integer _29dias) {
    this._29dias = _29dias;
  }

  public CuentasComercialesInner _59dias(Float _59dias) {
    this._59dias = _59dias;
    return this;
  }

   /**
   * Vencido de 30 a 59 días. Sólo con créditos abiertos.
   * @return _59dias
  **/
  @ApiModelProperty(example = "0")
  public Float get59dias() {
    return _59dias;
  }

  public void set59dias(Float _59dias) {
    this._59dias = _59dias;
  }

  public CuentasComercialesInner _89dias(Integer _89dias) {
    this._89dias = _89dias;
    return this;
  }

   /**
   * Vencido de 60 a 89 días. Sólo con créditos abiertos.
   * @return _89dias
  **/
  @ApiModelProperty(example = "0")
  public Integer get89dias() {
    return _89dias;
  }

  public void set89dias(Integer _89dias) {
    this._89dias = _89dias;
  }

  public CuentasComercialesInner _119dias(Float _119dias) {
    this._119dias = _119dias;
    return this;
  }

   /**
   * Vencido de 90 a 119 días. Sólo con créditos abiertos.
   * @return _119dias
  **/
  @ApiModelProperty(example = "0")
  public Float get119dias() {
    return _119dias;
  }

  public void set119dias(Float _119dias) {
    this._119dias = _119dias;
  }

  public CuentasComercialesInner _179dias(Integer _179dias) {
    this._179dias = _179dias;
    return this;
  }

   /**
   * Vencido de 120 a 179 días. Sólo con créditos abiertos.
   * @return _179dias
  **/
  @ApiModelProperty(example = "0")
  public Integer get179dias() {
    return _179dias;
  }

  public void set179dias(Integer _179dias) {
    this._179dias = _179dias;
  }

  public CuentasComercialesInner _180MasDias(Integer _180MasDias) {
    this._180MasDias = _180MasDias;
    return this;
  }

   /**
   * Vencido 180 días a más. Sólo con créditos abiertos.
   * @return _180MasDias
  **/
  @ApiModelProperty(example = "1500")
  public Integer get180MasDias() {
    return _180MasDias;
  }

  public void set180MasDias(Integer _180MasDias) {
    this._180MasDias = _180MasDias;
  }

  public CuentasComercialesInner actualizacion(String actualizacion) {
    this.actualizacion = actualizacion;
    return this;
  }

   /**
   * Último periodo de actualización (sólo con créditos abiertos), en el formato especificado (por defecto yyyy-MM).
   * @return actualizacion
  **/
  @ApiModelProperty(example = "2018-20")
  public String getActualizacion() {
    return actualizacion;
  }

  public void setActualizacion(String actualizacion) {
    this.actualizacion = actualizacion;
  }

  public CuentasComercialesInner historia(String historia) {
    this.historia = historia;
    return this;
  }

   /**
   * Patrón histórico de pagos
   * @return historia
  **/
  @ApiModelProperty(example = "111111111111------")
  public String getHistoria() {
    return historia;
  }

  public void setHistoria(String historia) {
    this.historia = historia;
  }

  public CuentasComercialesInner atrasoMayor(Integer atrasoMayor) {
    this.atrasoMayor = atrasoMayor;
    return this;
  }

   /**
   * Muestra la cantidad exacta de días de atraso cuando se reportan montos con vencimiento.
   * @return atrasoMayor
  **/
  @ApiModelProperty(example = "10")
  public Integer getAtrasoMayor() {
    return atrasoMayor;
  }

  public void setAtrasoMayor(Integer atrasoMayor) {
    this.atrasoMayor = atrasoMayor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CuentasComercialesInner cuentasComercialesInner = (CuentasComercialesInner) o;
    return Objects.equals(this.RFC, cuentasComercialesInner.RFC) &&
        Objects.equals(this.nombreOtorgante, cuentasComercialesInner.nombreOtorgante) &&
        Objects.equals(this.moneda, cuentasComercialesInner.moneda) &&
        Objects.equals(this.vigente, cuentasComercialesInner.vigente) &&
        Objects.equals(this.saldoTotal, cuentasComercialesInner.saldoTotal) &&
        Objects.equals(this._29dias, cuentasComercialesInner._29dias) &&
        Objects.equals(this._59dias, cuentasComercialesInner._59dias) &&
        Objects.equals(this._89dias, cuentasComercialesInner._89dias) &&
        Objects.equals(this._119dias, cuentasComercialesInner._119dias) &&
        Objects.equals(this._179dias, cuentasComercialesInner._179dias) &&
        Objects.equals(this._180MasDias, cuentasComercialesInner._180MasDias) &&
        Objects.equals(this.actualizacion, cuentasComercialesInner.actualizacion) &&
        Objects.equals(this.historia, cuentasComercialesInner.historia) &&
        Objects.equals(this.atrasoMayor, cuentasComercialesInner.atrasoMayor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RFC, nombreOtorgante, moneda, vigente, saldoTotal, _29dias, _59dias, _89dias, _119dias, _179dias, _180MasDias, actualizacion, historia, atrasoMayor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CuentasComercialesInner {\n");
    
    sb.append("    RFC: ").append(toIndentedString(RFC)).append("\n");
    sb.append("    nombreOtorgante: ").append(toIndentedString(nombreOtorgante)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    vigente: ").append(toIndentedString(vigente)).append("\n");
    sb.append("    saldoTotal: ").append(toIndentedString(saldoTotal)).append("\n");
    sb.append("    _29dias: ").append(toIndentedString(_29dias)).append("\n");
    sb.append("    _59dias: ").append(toIndentedString(_59dias)).append("\n");
    sb.append("    _89dias: ").append(toIndentedString(_89dias)).append("\n");
    sb.append("    _119dias: ").append(toIndentedString(_119dias)).append("\n");
    sb.append("    _179dias: ").append(toIndentedString(_179dias)).append("\n");
    sb.append("    _180MasDias: ").append(toIndentedString(_180MasDias)).append("\n");
    sb.append("    actualizacion: ").append(toIndentedString(actualizacion)).append("\n");
    sb.append("    historia: ").append(toIndentedString(historia)).append("\n");
    sb.append("    atrasoMayor: ").append(toIndentedString(atrasoMayor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
