/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * RespuestaRCCV2ClavePrevenciones
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class RespuestaRCCV2ClavePrevenciones {
  @SerializedName("nombreOtorgante")
  private String nombreOtorgante = null;

  @SerializedName("fechaReporte")
  private String fechaReporte = null;

  @SerializedName("numeroContrato")
  private String numeroContrato = null;

  @SerializedName("clavePrevencion")
  private CatalogoClavesPrevencion clavePrevencion = null;

  public RespuestaRCCV2ClavePrevenciones nombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
    return this;
  }

   /**
   * Nombre del otorgante que envían la calificacio.
   * @return nombreOtorgante
  **/
  @ApiModelProperty(example = "ADMINISTRACION CARTERA")
  public String getNombreOtorgante() {
    return nombreOtorgante;
  }

  public void setNombreOtorgante(String nombreOtorgante) {
    this.nombreOtorgante = nombreOtorgante;
  }

  public RespuestaRCCV2ClavePrevenciones fechaReporte(String fechaReporte) {
    this.fechaReporte = fechaReporte;
    return this;
  }

   /**
   * Fecha reporte, en el formato especificado (por defecto yyyy-MM-dd).
   * @return fechaReporte
  **/
  @ApiModelProperty(example = "2016-02-19")
  public String getFechaReporte() {
    return fechaReporte;
  }

  public void setFechaReporte(String fechaReporte) {
    this.fechaReporte = fechaReporte;
  }

  public RespuestaRCCV2ClavePrevenciones numeroContrato(String numeroContrato) {
    this.numeroContrato = numeroContrato;
    return this;
  }

   /**
   * Número de contrato.
   * @return numeroContrato
  **/
  @ApiModelProperty(example = "9484697777")
  public String getNumeroContrato() {
    return numeroContrato;
  }

  public void setNumeroContrato(String numeroContrato) {
    this.numeroContrato = numeroContrato;
  }

  public RespuestaRCCV2ClavePrevenciones clavePrevencion(CatalogoClavesPrevencion clavePrevencion) {
    this.clavePrevencion = clavePrevencion;
    return this;
  }

   /**
   * Get clavePrevencion
   * @return clavePrevencion
  **/
  @ApiModelProperty()
  public CatalogoClavesPrevencion getClavePrevencion() {
    return clavePrevencion;
  }

  public void setClavePrevencion(CatalogoClavesPrevencion clavePrevencion) {
    this.clavePrevencion = clavePrevencion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaRCCV2ClavePrevenciones respuestaRCCV2ClavePrevenciones = (RespuestaRCCV2ClavePrevenciones) o;
    return Objects.equals(this.nombreOtorgante, respuestaRCCV2ClavePrevenciones.nombreOtorgante) &&
        Objects.equals(this.fechaReporte, respuestaRCCV2ClavePrevenciones.fechaReporte) &&
        Objects.equals(this.numeroContrato, respuestaRCCV2ClavePrevenciones.numeroContrato) &&
        Objects.equals(this.clavePrevencion, respuestaRCCV2ClavePrevenciones.clavePrevencion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombreOtorgante, fechaReporte, numeroContrato, clavePrevencion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaRCCV2ClavePrevenciones {\n");
    
    sb.append("    nombreOtorgante: ").append(toIndentedString(nombreOtorgante)).append("\n");
    sb.append("    fechaReporte: ").append(toIndentedString(fechaReporte)).append("\n");
    sb.append("    numeroContrato: ").append(toIndentedString(numeroContrato)).append("\n");
    sb.append("    clavePrevencion: ").append(toIndentedString(clavePrevencion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
