/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * RespuestaRCCV2Declarativas
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class RespuestaRCCV2Declarativas {
  @SerializedName("declarativa")
  private String declarativa = null;

  @SerializedName("fechaDeclarativa")
  private String fechaDeclarativa = null;

  public RespuestaRCCV2Declarativas declarativa(String declarativa) {
    this.declarativa = declarativa;
    return this;
  }

   /**
   * Declarativa del acreditado en razón de su desacuerdo con el resultado del proceso de reclamación a una institución otorgante.
   * @return declarativa
  **/
  @ApiModelProperty(example = "NO ESTOY DE ACUERDO CON LO QUE FUE DICTAMINADO")
  public String getDeclarativa() {
    return declarativa;
  }

  public void setDeclarativa(String declarativa) {
    this.declarativa = declarativa;
  }

  public RespuestaRCCV2Declarativas fechaDeclarativa(String fechaDeclarativa) {
    this.fechaDeclarativa = fechaDeclarativa;
    return this;
  }

   /**
   * Fecha de declarativa de la persona, en el formato especificado (por defecto yyyy-MM-dd).
   * @return fechaDeclarativa
  **/
  @ApiModelProperty(example = "2012-12-01")
  public String getFechaDeclarativa() {
    return fechaDeclarativa;
  }

  public void setFechaDeclarativa(String fechaDeclarativa) {
    this.fechaDeclarativa = fechaDeclarativa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaRCCV2Declarativas respuestaRCCV2Declarativas = (RespuestaRCCV2Declarativas) o;
    return Objects.equals(this.declarativa, respuestaRCCV2Declarativas.declarativa) &&
        Objects.equals(this.fechaDeclarativa, respuestaRCCV2Declarativas.fechaDeclarativa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(declarativa, fechaDeclarativa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaRCCV2Declarativas {\n");
    
    sb.append("    declarativa: ").append(toIndentedString(declarativa)).append("\n");
    sb.append("    fechaDeclarativa: ").append(toIndentedString(fechaDeclarativa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
