/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
/**
 * RespuestaRCEV1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class RespuestaRCEV1 {
  @SerializedName("folioConsulta")
  private String folioConsulta = null;

  @SerializedName("folioOtorgante")
  private String folioOtorgante = null;

  @SerializedName("claveRetorno")
  private String claveRetorno = null;

  @SerializedName("claveRetornoSIC")
  private String claveRetornoSIC = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  @SerializedName("persona")
  private PersonaRespuesta persona = null;

  @SerializedName("clavesBanxico")
  private String clavesBanxico = null;

  @SerializedName("calificacionCartera")
  private List<RespuestaRCEV1CalificacionCartera> calificacionCartera = null;

  @SerializedName("clavePrevenciones")
  private List<RespuestaRCEV1ClavePrevenciones> clavePrevenciones = null;

  @SerializedName("consultasInstitucionales")
  private ConsultasInstitucionalesRCE consultasInstitucionales = null;

  @SerializedName("declarativas")
  private List<RespuestaRCCV2Declarativas> declarativas = null;

  @SerializedName("accionistas")
  private Accionistas accionistas = null;

  @SerializedName("avales")
  private Avales avales = null;

  @SerializedName("credito")
  private CreditosPM credito = null;

  @SerializedName("tipoReporte")
  private String tipoReporte = null;

  public RespuestaRCEV1 folioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
    return this;
  }

   /**
   * Número de folio de transacción asignado por Círculo de Crédito
   * @return folioConsulta
  **/
  @ApiModelProperty(example = "1984548323")
  public String getFolioConsulta() {
    return folioConsulta;
  }

  public void setFolioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
  }

  public RespuestaRCEV1 folioOtorgante(String folioOtorgante) {
    this.folioOtorgante = folioOtorgante;
    return this;
  }

   /**
   * Identificador de la consulta para verificaciones adicionales
   * @return folioOtorgante
  **/
  @ApiModelProperty(example = "7632")
  public String getFolioOtorgante() {
    return folioOtorgante;
  }

  public void setFolioOtorgante(String folioOtorgante) {
    this.folioOtorgante = folioOtorgante;
  }

  public RespuestaRCEV1 claveRetorno(String claveRetorno) {
    this.claveRetorno = claveRetorno;
    return this;
  }

   /**
   * Get claveRetorno
   * @return claveRetorno
  **/
  @ApiModelProperty(example = "1")
  public String getClaveRetorno() {
    return claveRetorno;
  }

  public void setClaveRetorno(String claveRetorno) {
    this.claveRetorno = claveRetorno;
  }

  public RespuestaRCEV1 claveRetornoSIC(String claveRetornoSIC) {
    this.claveRetornoSIC = claveRetornoSIC;
    return this;
  }

   /**
   * Clave de respuesta de otras SIC.
   * @return claveRetornoSIC
  **/
  @ApiModelProperty(example = "8")
  public String getClaveRetornoSIC() {
    return claveRetornoSIC;
  }

  public void setClaveRetornoSIC(String claveRetornoSIC) {
    this.claveRetornoSIC = claveRetornoSIC;
  }

  public RespuestaRCEV1 fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Fecha de la consulta
   * @return fechaConsulta
  **/
  @ApiModelProperty(example = "2024-08-07")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public RespuestaRCEV1 persona(PersonaRespuesta persona) {
    this.persona = persona;
    return this;
  }

   /**
   * Get persona
   * @return persona
  **/
  @ApiModelProperty()
  public PersonaRespuesta getPersona() {
    return persona;
  }

  public void setPersona(PersonaRespuesta persona) {
    this.persona = persona;
  }

  public RespuestaRCEV1 clavesBanxico(String clavesBanxico) {
    this.clavesBanxico = clavesBanxico;
    return this;
  }

   /**
   * Get clavesBanxico
   * @return clavesBanxico
  **/
  @ApiModelProperty()
  public String getClavesBanxico() {
    return clavesBanxico;
  }

  public void setClavesBanxico(String clavesBanxico) {
    this.clavesBanxico = clavesBanxico;
  }

  public RespuestaRCEV1 calificacionCartera(List<RespuestaRCEV1CalificacionCartera> calificacionCartera) {
    this.calificacionCartera = calificacionCartera;
    return this;
  }

  public RespuestaRCEV1 addCalificacionCarteraItem(RespuestaRCEV1CalificacionCartera calificacionCarteraItem) {
    if (this.calificacionCartera == null) {
      this.calificacionCartera = new ArrayList<RespuestaRCEV1CalificacionCartera>();
    }
    this.calificacionCartera.add(calificacionCarteraItem);
    return this;
  }

   /**
   * Disposiciones de carácter general aplicables a las instituciones de crédito.
   * @return calificacionCartera
  **/
  @ApiModelProperty()
  public List<RespuestaRCEV1CalificacionCartera> getCalificacionCartera() {
    return calificacionCartera;
  }

  public void setCalificacionCartera(List<RespuestaRCEV1CalificacionCartera> calificacionCartera) {
    this.calificacionCartera = calificacionCartera;
  }

  public RespuestaRCEV1 clavePrevenciones(List<RespuestaRCEV1ClavePrevenciones> clavePrevenciones) {
    this.clavePrevenciones = clavePrevenciones;
    return this;
  }

  public RespuestaRCEV1 addClavePrevencionesItem(RespuestaRCEV1ClavePrevenciones clavePrevencionesItem) {
    if (this.clavePrevenciones == null) {
      this.clavePrevenciones = new ArrayList<RespuestaRCEV1ClavePrevenciones>();
    }
    this.clavePrevenciones.add(clavePrevencionesItem);
    return this;
  }

   /**
   * Get clavePrevenciones
   * @return clavePrevenciones
  **/
  @ApiModelProperty()
  public List<RespuestaRCEV1ClavePrevenciones> getClavePrevenciones() {
    return clavePrevenciones;
  }

  public void setClavePrevenciones(List<RespuestaRCEV1ClavePrevenciones> clavePrevenciones) {
    this.clavePrevenciones = clavePrevenciones;
  }

  public RespuestaRCEV1 consultasInstitucionales(ConsultasInstitucionalesRCE consultasInstitucionales) {
    this.consultasInstitucionales = consultasInstitucionales;
    return this;
  }

   /**
   * Get consultasInstitucionales
   * @return consultasInstitucionales
  **/
  @ApiModelProperty()
  public ConsultasInstitucionalesRCE getConsultasInstitucionales() {
    return consultasInstitucionales;
  }

  public void setConsultasInstitucionales(ConsultasInstitucionalesRCE consultasInstitucionales) {
    this.consultasInstitucionales = consultasInstitucionales;
  }

  public RespuestaRCEV1 declarativas(List<RespuestaRCCV2Declarativas> declarativas) {
    this.declarativas = declarativas;
    return this;
  }

  public RespuestaRCEV1 addDeclarativasItem(RespuestaRCCV2Declarativas declarativasItem) {
    if (this.declarativas == null) {
      this.declarativas = new ArrayList<RespuestaRCCV2Declarativas>();
    }
    this.declarativas.add(declarativasItem);
    return this;
  }

   /**
   * Get declarativas
   * @return declarativas
  **/
  @ApiModelProperty()
  public List<RespuestaRCCV2Declarativas> getDeclarativas() {
    return declarativas;
  }

  public void setDeclarativas(List<RespuestaRCCV2Declarativas> declarativas) {
    this.declarativas = declarativas;
  }

  public RespuestaRCEV1 accionistas(Accionistas accionistas) {
    this.accionistas = accionistas;
    return this;
  }

   /**
   * Get accionistas
   * @return accionistas
  **/
  @ApiModelProperty()
  public Accionistas getAccionistas() {
    return accionistas;
  }

  public void setAccionistas(Accionistas accionistas) {
    this.accionistas = accionistas;
  }

  public RespuestaRCEV1 avales(Avales avales) {
    this.avales = avales;
    return this;
  }

   /**
   * Get avales
   * @return avales
  **/
  @ApiModelProperty()
  public Avales getAvales() {
    return avales;
  }

  public void setAvales(Avales avales) {
    this.avales = avales;
  }

  public RespuestaRCEV1 credito(CreditosPM credito) {
    this.credito = credito;
    return this;
  }

   /**
   * Get credito
   * @return credito
  **/
  @ApiModelProperty()
  public CreditosPM getCredito() {
    return credito;
  }

  public void setCredito(CreditosPM credito) {
    this.credito = credito;
  }

  public RespuestaRCEV1 tipoReporte(String tipoReporte) {
    this.tipoReporte = tipoReporte;
    return this;
  }

   /**
   * Get tipoReporte
   * @return tipoReporte
  **/
  @ApiModelProperty(example = "31")
  public String getTipoReporte() {
    return tipoReporte;
  }

  public void setTipoReporte(String tipoReporte) {
    this.tipoReporte = tipoReporte;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaRCEV1 respuestaRCEV1 = (RespuestaRCEV1) o;
    return Objects.equals(this.folioConsulta, respuestaRCEV1.folioConsulta) &&
        Objects.equals(this.folioOtorgante, respuestaRCEV1.folioOtorgante) &&
        Objects.equals(this.claveRetorno, respuestaRCEV1.claveRetorno) &&
        Objects.equals(this.claveRetornoSIC, respuestaRCEV1.claveRetornoSIC) &&
        Objects.equals(this.fechaConsulta, respuestaRCEV1.fechaConsulta) &&
        Objects.equals(this.persona, respuestaRCEV1.persona) &&
        Objects.equals(this.clavesBanxico, respuestaRCEV1.clavesBanxico) &&
        Objects.equals(this.calificacionCartera, respuestaRCEV1.calificacionCartera) &&
        Objects.equals(this.clavePrevenciones, respuestaRCEV1.clavePrevenciones) &&
        Objects.equals(this.consultasInstitucionales, respuestaRCEV1.consultasInstitucionales) &&
        Objects.equals(this.declarativas, respuestaRCEV1.declarativas) &&
        Objects.equals(this.accionistas, respuestaRCEV1.accionistas) &&
        Objects.equals(this.avales, respuestaRCEV1.avales) &&
        Objects.equals(this.credito, respuestaRCEV1.credito) &&
        Objects.equals(this.tipoReporte, respuestaRCEV1.tipoReporte);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folioConsulta, folioOtorgante, claveRetorno, claveRetornoSIC, fechaConsulta, persona, clavesBanxico, calificacionCartera, clavePrevenciones, consultasInstitucionales, declarativas, accionistas, avales, credito, tipoReporte);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaRCEV1 {\n");
    
    sb.append("    folioConsulta: ").append(toIndentedString(folioConsulta)).append("\n");
    sb.append("    folioOtorgante: ").append(toIndentedString(folioOtorgante)).append("\n");
    sb.append("    claveRetorno: ").append(toIndentedString(claveRetorno)).append("\n");
    sb.append("    claveRetornoSIC: ").append(toIndentedString(claveRetornoSIC)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    persona: ").append(toIndentedString(persona)).append("\n");
    sb.append("    clavesBanxico: ").append(toIndentedString(clavesBanxico)).append("\n");
    sb.append("    calificacionCartera: ").append(toIndentedString(calificacionCartera)).append("\n");
    sb.append("    clavePrevenciones: ").append(toIndentedString(clavePrevenciones)).append("\n");
    sb.append("    consultasInstitucionales: ").append(toIndentedString(consultasInstitucionales)).append("\n");
    sb.append("    declarativas: ").append(toIndentedString(declarativas)).append("\n");
    sb.append("    accionistas: ").append(toIndentedString(accionistas)).append("\n");
    sb.append("    avales: ").append(toIndentedString(avales)).append("\n");
    sb.append("    credito: ").append(toIndentedString(credito)).append("\n");
    sb.append("    tipoReporte: ").append(toIndentedString(tipoReporte)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
