/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.RCCPM.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * RespuestaRCCV2ClavesBanxico
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-10T17:56:34.445680493Z[GMT]")

public class RespuestaRCCV2ClavesBanxico {
  @SerializedName("claveBanxico1")
  private String claveBanxico1 = null;

  @SerializedName("claveBanxico2")
  private String claveBanxico2 = null;

  @SerializedName("claveBanxico3")
  private String claveBanxico3 = null;

  public RespuestaRCCV2ClavesBanxico claveBanxico1(String claveBanxico1) {
    this.claveBanxico1 = claveBanxico1;
    return this;
  }

   /**
   * Get claveBanxico1
   * @return claveBanxico1
  **/
  @ApiModelProperty()
  public String getClaveBanxico1() {
    return claveBanxico1;
  }

  public void setClaveBanxico1(String claveBanxico1) {
    this.claveBanxico1 = claveBanxico1;
  }

  public RespuestaRCCV2ClavesBanxico claveBanxico2(String claveBanxico2) {
    this.claveBanxico2 = claveBanxico2;
    return this;
  }

   /**
   * Get claveBanxico2
   * @return claveBanxico2
  **/
  @ApiModelProperty()
  public String getClaveBanxico2() {
    return claveBanxico2;
  }

  public void setClaveBanxico2(String claveBanxico2) {
    this.claveBanxico2 = claveBanxico2;
  }

  public RespuestaRCCV2ClavesBanxico claveBanxico3(String claveBanxico3) {
    this.claveBanxico3 = claveBanxico3;
    return this;
  }

   /**
   * Get claveBanxico3
   * @return claveBanxico3
  **/
  @ApiModelProperty()
  public String getClaveBanxico3() {
    return claveBanxico3;
  }

  public void setClaveBanxico3(String claveBanxico3) {
    this.claveBanxico3 = claveBanxico3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaRCCV2ClavesBanxico respuestaRCCV2ClavesBanxico = (RespuestaRCCV2ClavesBanxico) o;
    return Objects.equals(this.claveBanxico1, respuestaRCCV2ClavesBanxico.claveBanxico1) &&
        Objects.equals(this.claveBanxico2, respuestaRCCV2ClavesBanxico.claveBanxico2) &&
        Objects.equals(this.claveBanxico3, respuestaRCCV2ClavesBanxico.claveBanxico3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claveBanxico1, claveBanxico2, claveBanxico3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaRCCV2ClavesBanxico {\n");
    
    sb.append("    claveBanxico1: ").append(toIndentedString(claveBanxico1)).append("\n");
    sb.append("    claveBanxico2: ").append(toIndentedString(claveBanxico2)).append("\n");
    sb.append("    claveBanxico3: ").append(toIndentedString(claveBanxico3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
